# Generated by Django 4.0.6 on 2022-09-18 13:49

import ckeditor_uploader.fields
import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='our story')),
                ('our_story_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our story')),
                ('our_story_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our story')),
                ('our_story_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our story')),
                ('our_story_image', models.ImageField(upload_to='about_img', verbose_name='our store image')),
                ('our_mission', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='our mission')),
                ('our_mission_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our mission')),
                ('our_mission_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our mission')),
                ('our_mission_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our mission')),
                ('our_mission_image', models.ImageField(null=True, upload_to='about_img', verbose_name='our mission image')),
                ('banner_image', models.ImageField(upload_to='about_img', verbose_name='banner image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=4), django.core.validators.MaxLengthValidator(limit_value=30)], verbose_name='name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('phone', models.CharField(max_length=13, null=True, validators=[config.validators.PhoneValidator()], verbose_name='phone')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='MenBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections', models.CharField(max_length=100, verbose_name='collections')),
                ('collections_en', models.CharField(max_length=100, null=True, verbose_name='collections')),
                ('collections_uz', models.CharField(max_length=100, null=True, verbose_name='collections')),
                ('collections_ru', models.CharField(max_length=100, null=True, verbose_name='collections')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='men_banner')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'men_banner',
                'verbose_name_plural': 'men_banners',
            },
        ),
        migrations.CreateModel(
            name='WomenBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections', models.CharField(max_length=100, verbose_name='collections')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='men_banner')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'women_banner',
                'verbose_name_plural': 'women_banners',
            },
        ),
    ]
