# Generated by Django 4.0.6 on 2022-08-13 03:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_womenbannermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='our story')),
                ('our_mission', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='our mission')),
                ('banner_image', models.ImageField(upload_to='about_img', verbose_name='banner image')),
                ('about_image', models.ImageField(upload_to='about_img', verbose_name='about image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
    ]
