# Generated by Django 4.0.6 on 2022-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_aboutmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='about_image',
            new_name='our_story_image',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='our_mission_image',
            field=models.ImageField(null=True, upload_to='about_img', verbose_name='about image'),
        ),
    ]
