# Generated by Django 4.0.6 on 2022-08-14 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_about_image_aboutmodel_our_story_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='our_mission_image',
            field=models.ImageField(null=True, upload_to='about_img', verbose_name='our mission image'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='our_story_image',
            field=models.ImageField(upload_to='about_img', verbose_name='our store image'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='name'),
        ),
    ]
