# Generated by Django 4.0.6 on 2022-08-14 22:05

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contactmodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=4), django.core.validators.MaxLengthValidator(limit_value=30)], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=13, null=True, validators=[config.validators.PhoneValidator()], verbose_name='phone'),
        ),
    ]
