# Generated by Django 4.0.6 on 2022-08-16 11:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_contactmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='our_mission_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our mission'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='our_mission_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our mission'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='our_mission_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our mission'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='our_story_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our story'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='our_story_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our story'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='our_story_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='our story'),
        ),
    ]
