# Generated by Django 4.0.6 on 2022-08-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_aboutmodel_our_mission_en_aboutmodel_our_mission_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menbannermodel',
            name='collections_en',
            field=models.CharField(max_length=100, null=True, verbose_name='collections'),
        ),
        migrations.AddField(
            model_name='menbannermodel',
            name='collections_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='collections'),
        ),
        migrations.AddField(
            model_name='menbannermodel',
            name='collections_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='collections'),
        ),
        migrations.AddField(
            model_name='menbannermodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='menbannermodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='menbannermodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
