# Generated by Django 4.0.6 on 2022-10-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='email',
        ),
    ]
