# Generated by Django 4.0.6 on 2022-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image_2',
            field=models.ImageField(null=True, upload_to='posts_2', verbose_name='image_2'),
        ),
    ]
