# Generated by Django 4.0.6 on 2022-09-20 13:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('image', models.ImageField(null=True, upload_to='bar_categories', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'bar_category',
                'verbose_name_plural': 'bar_categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('code', models.CharField(max_length=60, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='ProductDetailImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('image_1', models.ImageField(null=True, upload_to='detail_image', verbose_name='image_1')),
                ('image_2', models.ImageField(null=True, upload_to='detail_image', verbose_name='image_2')),
                ('image_3', models.ImageField(null=True, upload_to='detail_image', verbose_name='image_3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'detail_image',
                'verbose_name_plural': 'detail_images',
            },
        ),
        migrations.CreateModel(
            name='ProductTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=60, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('short_description', models.CharField(max_length=255, verbose_name='short description')),
                ('short_description_en', models.CharField(max_length=255, null=True, verbose_name='short description')),
                ('short_description_uz', models.CharField(max_length=255, null=True, verbose_name='short description')),
                ('short_description_ru', models.CharField(max_length=255, null=True, verbose_name='short description')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='long description')),
                ('long_description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long description')),
                ('long_description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long description')),
                ('long_description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long description')),
                ('price', models.FloatField(verbose_name='price')),
                ('real_price', models.FloatField(default=0, verbose_name='real price')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='discount')),
                ('main_image', models.ImageField(upload_to='products', verbose_name='main image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='sku')),
                ('bar_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='shop.barcategorymodel', verbose_name='bar_categories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='shop.categorymodel', verbose_name='category')),
                ('colors', models.ManyToManyField(related_name='products', to='shop.colormodel', verbose_name='colors')),
                ('detail_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.productdetailimagemodel', verbose_name='detail images')),
                ('sizes', models.ManyToManyField(related_name='products', to='shop.sizemodel', verbose_name='sizes')),
                ('tags', models.ManyToManyField(related_name='products', to='shop.producttagmodel', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlists',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
