# Generated by Django 4.0.6 on 2022-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='producttagmodel',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
    ]
