# Generated by Django 4.0.6 on 2022-09-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shophistorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopHistoryModel',
        ),
    ]
