# Generated by Django 4.0.6 on 2022-08-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'bar_category',
                'verbose_name_plural': 'bar_categories',
            },
        ),
    ]
