# Generated by Django 4.0.6 on 2022-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shophistorymodel_delete_shophistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shophistorymodel',
            name='phone',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
    ]
