# Generated by Django 4.0.6 on 2022-08-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_barcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='bar_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='shop.barcategorymodel', verbose_name='bar_categories'),
        ),
    ]
