# Generated by Django 4.0.6 on 2022-08-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productmodel_bar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcategorymodel',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
