# Generated by Django 4.0.6 on 2022-08-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_barcategorymodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcategorymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='bar_categories', verbose_name='image'),
        ),
    ]
