# Generated by Django 4.0.6 on 2022-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productmodel_detail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
    ]
