# Generated by Django 4.0.6 on 2022-08-16 12:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productmodel_detail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcategorymodel',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='barcategorymodel',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='barcategorymodel',
            name='name_uz',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='barcategorymodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='barcategorymodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='barcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_uz',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_uz',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productdetailimagemodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productdetailimagemodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productdetailimagemodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='name_uz',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
    ]
