# Generated by Django 4.0.6 on 2022-08-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productdetailimagemodel_image_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailimagemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='productdetailimagemodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='productdetailimagemodel',
            name='title_uz',
        ),
    ]
