# Generated by Django 4.0.6 on 2022-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='comment',
            new_name='city',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
