# Generated by Django 4.0.6 on 2022-09-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profilemodel_comment_alter_profilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='comment',
        ),
    ]
