# Generated by Django 4.0.6 on 2022-09-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profilemodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
