# Generated by Django 4.0.6 on 2022-09-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profilemodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='comment',
        ),
    ]
