# Generated by Django 4.0.6 on 2022-09-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shophistorymodel',
            old_name='email',
            new_name='gmail',
        ),
    ]
