# Generated by Django 4.0.6 on 2022-09-19 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_delete_shophistorymodel'),
        ('orders', '0002_rename_email_shophistorymodel_gmail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopHistoryModel',
            new_name='OrderHistoryModel',
        ),
    ]
