# Generated by Django 4.0.6 on 2022-09-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderhistorymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
