# Generated by Django 4.0.6 on 2022-09-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderhistorymodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
